models/Tasks.php
<?php

class Tasks extends CActiveRecord{
	const PAGE_SIZE=10;

	//public $startdate;
	//public $starttime;
	public $sendsms;

	/*public function setKontragentID($netid){
  		 self::find(array(
	  		'select'=>'title',
		'condition'=>'postID=:postID',
   		'params'=>array(':postID'=>10),);

	}   */

	public static function model($className=__CLASS__){
		return parent::model($className);
	}

	public function relations()
    {
        return array(
			'executor'=>array(self::BELONGS_TO, 'Users', 'id_executor'),
			'author'=>array(self::BELONGS_TO, 'Users', 'id_author'),
			'kontr'=>array(self::BELONGS_TO, 'Kontragents', 'id_kontragent'), //****
		);
    }


	public function rules(){ //определить правила для данных вводимых пользователем.
		return array(
			array('startdate','required'),
			array('description,stopdate,id_executor,id_owner,notify_execute,
				ex_description,state,important,id_kontragent, sendsms ,price ,accept_execute, executedate','length'), //***********
		);
	}

	public function tableName(){
		return 'tasks';
	}

	public function attributeLabels(){
		return array(
			'startdate' => 'Дата/Время',
			'id_executor' => 'Исполнитель',
			'id_kontragent' => 'Организация',
			'id_owner' => 'Инициатор',
			'description' => 'Описание',
			'important' => 'Важно',
			'sendsms' => 'Оповестить исполнителя',
			'price' => 'Стоимость',
			'accept_execute' => 'Подтверждать выполнение',
		);
	}

}

controllers/TasksController.php
<?php
class TasksController extends CController
{
	public $win_title='Задачи';
	const PAGE_SIZE=10;
	private $_model;
	public $layout="internal";
	
	public function filters(){
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	public function accessRules(){
		return array(
			array('allow',  // allow all users to perform 'list' and 'show' actions
				'actions'=>array('HelpDeskTaskCreate'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated users to access all actions
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}


	public function actionIndex(){
		if (!isset($_GET['timestamp'])) $currenttimestamp = time();
		else $currenttimestamp = $_GET['timestamp'];

		$dataProvider=new CActiveDataProvider('Tasks', array(
						'criteria'=>array(
							'condition'=>"id_owner=:currentorg  AND (startdate < :currentstopdate AND (stopdate > :currentstartdate OR stopdate = '0000-00-00 00:00:00'))",
							'params'=>array(':currentstartdate'=>date('Y-m-d', $currenttimestamp).' 00:00:00',
											':currentstopdate'=>date('Y-m-d', $currenttimestamp).' 23:59:59',
											':currentorg'=>Yii::app()->user->org,
											),
						),
    			'pagination'=>array(
        				'pageSize'=>20,
    			),
		));


		$this->win_title='Все задачи на '.date('d.m.Y',$currenttimestamp);
		$this->render('index',array('dataProvider'=>$dataProvider));
	}

	public function actionCreate(){
		$model=new Tasks;
		$this->win_title.=' Новая';
		
		if (!isset($_GET['timestamp'])) $currenttimestamp = time();
		else $currenttimestamp = $_GET['timestamp'];
		
		$model->startdate = date('Y-m-d H:i:s',$currenttimestamp);
		$model->sendsms=1;
		
		if(isset($_POST['Tasks'])){
			$model->attributes = $_POST['Tasks'];
			$model->startdate = $_POST['startdate'].' '.$_POST['starttime']; //Старт задания
			$model->executedate = $_POST['executedate'].' '.$_POST['executetime']; //Дата исполнения
			$model->id_author = Yii::app()->user->getId(); //Автор задания текущий пользователь
			$model->id_owner = Yii::app()->user->org;
			$model->ex_description='';
			if($model->save()){
				if ($model->id_executor && $model->sendsms){
					//если установлен исполнитель и галочка отправки, отправляем SMS сообщение
					$textmsg = $model->kontr->name."\n";
					$textmsg.= "Адрес: ".$model->kontr->addr."\n";
					$textmsg.= $model->description."\n";
			
					Glob::sendUserMsg($model->id_executor,$textmsg);
				}
				$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		$this->render('create',array('model'=>$model));
	}

	public function actionHelpDeskTaskCreate(){  //задачи от хелп деска новая версия
		
		//Формируем сообщение 
		$textmsg = "****Comty.ru****\n\n";
		$desc = $_POST['desc'];
		
		//Ищем компьютер по IP адресу отправителя
		if ($model = Computers::model()->getByIP($_SERVER['REMOTE_ADDR'])){

		    //Если найден компьютер 
		    //Определяем контору которой принадлежит данный комп
		    $textmsg.= $model->org->name."\n";
		    $textmsg.= "Адрес: ".$model->org->addr."\n";
		    $textmsg.= "Компьютер: ".$model->name."\n";
		    $textmsg.= "IP-адрес: ".$_SERVER['REMOTE_ADDR']."\n";
		    
		    //Проверяем владельца компьютера
		    if ($model->id_owner != 0){
			$textmsg.= "Отправитель: ".$model->owner->name."\n";
			$textmsg.= "Телефон: ".$model->owner->phone."\n";
		    }else
			$textmsg.= "Отправитель: Нет данных \n"; //Если нет то говорим что комп без хозяина
		
		    $textmsg.= "\n".$desc."\n";
		
		//Создаем задачу с нужными параметрами
		$task=new Tasks;
		$task->startdate = date('Y-m-d H:i:s',time());
		$task->description = $desc;
		$task->id_executor = '';
		$task->id_kontragent = $model->id_org;
		$task->ex_description='';
		$task->save();
		
		//Oповещаем ответственных
		    foreach($model->org->otv as $item){
			Glob::sendUserMsg($item->id_user,$textmsg);
		    }
		
		}
		else{
		    //Если компьютер не найден в базе то добавляем только IP адрес
		    //Желательно чтобы так-же создавал задачу для деспечера чтобы заполнила базу
		
		//Создаем задачу с нужными параметрами
		$model=new Tasks;
		$model->startdate = date('Y-m-d H:i:s',time());
		$model->description = $desc.$_SERVER['REMOTE_ADDR'];
		$model->id_executor = '';
		$model->id_kontragent = 0;
		$model->ex_description='';
		$model->save();
		
		}
	}

	public function actionUpdate(){
		$model=$this->loadModel();
		$this->win_title='Редактирование задачи';

			if(isset($_POST['Tasks'])){
					$model->attributes = $_POST['Tasks'];
					//if($model->validate()){
					
					$model->startdate = $_POST['startdate'].' '.$_POST['starttime']; //Старт задания
					$model->executedate = $_POST['executedate'].' '.$_POST['executetime']; //Дата исполнения
					
					if($model->save()){
							
						if ($model->id_executor && $model->sendsms){
						    //если установлен исполнитель и галочка отправки, отправляем SMS сообщение
							$textmsg = $model->kontr->name."\n";
							$textmsg.= "Адрес: ".$model->kontr->addr."\n";
							$textmsg.= $model->description."\n";
			
							Glob::sendUserMsg($model->id_executor,$textmsg);
						}
						$this->redirect(Yii::app()->user->returnUrl);
						}
					//}
				}

			$this->render('update',array('model'=>$model));
	}

	public function actionDelete(){
		$this->loadModel()->delete();
		$this->redirect(Yii::app()->user->returnUrl);
	}

	public function actionIndexByExecutor(){
		Yii::app()->user->setReturnUrl(Yii::app()->getRequest()->getUrl()); //Запоминаем текущую страницу для редиректа
	
		if (!isset($_GET['timestamp'])) $currenttimestamp = time();
		else $currenttimestamp = $_GET['timestamp'];

		$q = new CDbCriteria( array(
							'condition'=>"id_owner=:currentorg  AND (startdate < :currentstopdate AND (stopdate > :currentstartdate OR stopdate = '0000-00-00 00:00:00'))",
							'order'=>'id_executor',
							'params'=>array(':currentstartdate'=>date('Y-m-d', $currenttimestamp).' 00:00:00',
											':currentstopdate'=>date('Y-m-d', $currenttimestamp).' 23:59:59',
											':currentorg'=>Yii::app()->user->org,
											),
		));

		$model=Tasks::model()->findAll($q);
		
		if (!isset($_GET['print'])){
			$this->win_title='Все задачи (по исполнителю) на '.date('d.m.Y',$currenttimestamp);
			$this->render('indexbyexecutor',array('model'=>$model));
		}
		else
			$this->renderPartial('printbyexecutor',array('model'=>$model));
			
	}

	public function actionIndexByOrg(){
		Yii::app()->user->setReturnUrl(Yii::app()->getRequest()->getUrl()); //Запоминаем текущую страницу для редиректа
		
		if (!isset($_GET['timestamp'])) $currenttimestamp = time();
		else $currenttimestamp = $_GET['timestamp'];

		$q = new CDbCriteria( array(
							'condition'=>"id_owner=:currentorg  AND (startdate < :currentstopdate AND (stopdate > :currentstartdate OR stopdate = '0000-00-00 00:00:00'))",
							'order'=>'id_kontragent',
							'params'=>array(':currentstartdate'=>date('Y-m-d', $currenttimestamp).' 00:00:00',
											':currentstopdate'=>date('Y-m-d', $currenttimestamp).' 23:59:59',
											':currentorg'=>Yii::app()->user->org,
											),
		));

		$model=Tasks::model()->findAll($q);
		
		if (!isset($_GET['print'])){
			$this->win_title='Все задачи (по организации) на '.date('d.m.Y',$currenttimestamp);
			$this->render('indexbyorg',array('model'=>$model));
		}
		else
			$this->renderPartial('printbyorg',array('model'=>$model));		
	}
	
	public function actionCorrect(){
		$model=$this->loadModel();
		$model->state = 0;
		$model->save();
		$this->redirect(Yii::app()->user->returnUrl);
	}

	public function actionUploadFile(){
		$form=new UploadFileForm;
		$this->win_title='Загрузка файла';
		$id = $_GET['id'];
		
		
		if(isset($_POST['UploadFileForm'])){
		    $form->attributes = $_POST['UploadFileForm'];
		    $form->ufile = CUploadedFile::getInstance($form,'ufile');
		    $filepath = Yii::app()->basePath.'/../files/tasks/'.$id;
		    Glob::mkpath($filepath);
		    $form->ufile->saveAs($filepath.'/'.$form->ufile->name);
		    $this->redirect(Yii::app()->user->returnUrl);
		}
		
		$this->render('_form_file_upload',array('model'=>$form));
	}

	public function actionDelUploadFile($id,$filename){
		$filepath = Yii::app()->basePath.'/../files/tasks/'.$id.'/'.$filename;
		unlink($filepath);
		$this->redirect(Yii::app()->user->returnUrl);
	}

	public function actionAcceptExecute($id,$acpt){
		$model = Tasks::model()->findbyPk($id);
		$model->state = $acpt;
		$model->save();
		
		if($model->price <> 0){
			$tr = new Finance;
			$tr->sum = $model->price;
			$tr->id_user = $model->id_executor;
			$tr->description = 'Начисление по задаче № '.$model->id;
			$tr->save();
		} 
		
		$this->redirect(Yii::app()->user->returnUrl);
	}

	public function actionExecute(){//Выполнение задачи
		$model=$this->loadModel();
		$this->win_title.=' Выполнить';		
		
		if(isset($_POST['Tasks'])){
					
					$model->attributes = $_POST['Tasks'];

					if(($model->state == 1)and($model->accept_execute == 1)) $model->state = 3;
					if(($model->state == 1)or($model->state == 3)) $model->stopdate = date('Y-m-d H:i:s', time());
										
					if($model->notify_execute){
						//Уведомлять при выполнении автора задания
						Glob::sendUserMsg($model->id_owner,'Задание '.$model->id.' выполнено!');
					}

					if($model->save()){
							$this->redirect(Yii::app()->user->returnUrl);
						}
				}
				

		$this->render('execute',array('model'=>$model,));
	}
	
	public function actionPrintUserTasks(){
		
		$currenttimestamp = time();
		
		$q = new CDbCriteria( array(							
							'order'=>'id_kontragent',
							'condition'=>"startdate < :currentstopdate AND (stopdate > :currentstartdate OR stopdate = '0000-00-00 00:00:00') AND id_executor = :uid",
							'params'=>array(':currentstartdate'=>date('Y-m-d', $currenttimestamp).' 00:00:00',
											':currentstopdate'=>date('Y-m-d', $currenttimestamp).' 23:59:59',
											':uid'=>$_GET['id'],
											),
		));

views/tasks/_form.php
<?php echo CHtml::beginForm(); ?>
<?php echo CHtml::errorSummary($model); ?>
<?php $dt = explode(" ",$model->startdate);?>
<?php $dt1 = explode(" ",$model->executedate);?>

<br>
<table width=100%>
<tr>
    <td style="width:200px">Первый запуск (Дата/Время)</td>
    <td><?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
								    'language'=>'ru',
									'name'=>'startdate',
									'value' => $dt[0],
								    'options'=>array(
									'showAnim'=>'fold',
									'dateFormat'=>'yy-mm-dd',
									'buttonImageOnly' => true,
									),
								    'htmlOptions'=>array(
									'maxlength'=>7,
									'size' => 8,
									),
	)); ?>
	&nbsp;&nbsp;/&nbsp;

	<?php
		$this->widget('CMaskedTextField',array(
					'name' => 'starttime',
					'mask'=>'99:99:99',
					'value' => $dt[1],
					'htmlOptions' => array('size' => 6)
		));
	?>
    </td>
</tr>

<tr>
    <td style="width:200px">Выполнить до (Дата/Время)</td>
    <td><?php $this->widget('zii.widgets.jui.CJuiDatePicker', array(
								    'language'=>'ru',
									'name'=>'executedate',
									'value' => $dt1[0],
								    'options'=>array(
									'showAnim'=>'fold',
									'dateFormat'=>'yy-mm-dd',
									'buttonImageOnly' => true,
									),
								    'htmlOptions'=>array(
									'maxlength'=>7,
									'size' => 8,
									),
	)); ?>
	&nbsp;&nbsp;/&nbsp;

	<?php
		$this->widget('CMaskedTextField',array(
					'name' => 'executetime',
					'mask'=>'99:99:99',
					'value' => $dt1[1],
					'htmlOptions' => array('size' => 6)
		));
	?>
    </td>
</tr>


<tr>
	<td><?php echo CHtml::activeLabelEx($model,'id_executor');?></td>
	<td><?php
			//Готовим список выбора пользователей
			$usrlist = CHtml::listData(Users::model()->with('person')->findAll(array('order'=>'person.name','condition'=>"person.id_org=".Yii::app()->user->org,)),'id','person.name');
			$usrlist = array('') + $usrlist;
			echo CHtml::activeDropDownList($model,'id_executor',$usrlist,array('class'=>'text_edit','style'=>'width:400px;'));
		?>
	</td>
</tr>
<tr>
	<td><?php echo CHtml::activeLabelEx($model,'sendsms');?></td>
	<td><?php echo CHtml::activeCheckBox($model,'sendsms'); ?></td>
</tr>
<tr>
	<td><?php echo CHtml::activeLabelEx($model,'id_kontragent');?></td>
	<td><?php
			//Готовим список выбора организаций
			$kntrlist = CHtml::listData(Kontragents::model()->findAll(array('order'=>'name','condition'=>'id_owner='.Yii::app()->user->org.' OR '.'id='.Yii::app()->user->org)),'id','name');
			$kntrlist = array('') + $kntrlist;  //добавляет пустое поле в выподающий список
			echo CHtml::activeDropDownList($model,'id_kontragent',$kntrlist,array('class'=>'text_edit','style'=>'width:400px;'));
		?>
	</td>
</tr>

<tr>
	<td>Уведомлять при выполнении</td>
	<td><?php echo CHtml::activeCheckBox($model,'notify_execute'); ?></td>
</tr>



<tr>
	<td><?php echo CHtml::activeLabelEx($model,'important');?></td>
	<td><?php echo CHtml::activeCheckBox($model,'important'); ?></td>
</tr>

<tr>
	<td><?php echo CHtml::activeLabelEx($model,'accept_execute');?></td>
	<td><?php echo CHtml::activeCheckBox($model,'accept_execute'); ?></td>
</tr>

<tr>
	<td><?php echo CHtml::activeLabelEx($model,'price');?></td>
	<td><?php echo CHtml::activeTextField($model,'price',array('class'=>'text_edit','style'=>'width:100px;')); ?></td>
</tr>

<tr>
	<td><?php echo CHtml::activeLabelEx($model,'description');?></td>
	<td><?php echo CHtml::activeTextArea($model,'description',array('class'=>'text_edit','style'=>'width:400px;')); ?></td>
</tr>

<tr>
	<td colspan=2 align="center"><?php echo chtml::submitbutton('Сохранить',array('class'=>'bt','style'=>'width:90px;')); ?></td>
</tr>

</table>
<?php echo CHtml::endForm(); ?>

views/tasks/_form_file_upload.php
<?php echo CHtml::beginForm('', 'post', array('enctype' => 'multipart/form-data')); ?>
<?php echo CHtml::errorSummary($model); ?>
    <table width=100%>
	<tr>
	    <td style="width:150px"><?php echo CHtml::activeLabelEx($model,'ufile');?></td>
	    <td><?php echo CHtml::activeFileField($model,'ufile',array('class'=>'text_edit')); ?></td>
	</tr>

	<tr>
	    <td colspan=2 align="center"><?php echo CHtml::submitbutton('Сохранить',array('class'=>'bt','style'=>'width:90px;')); ?></td>
	</tr>
    </table>
<?php  echo CHtml::endForm(); ?>

views/tasks/create.php
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

views/tasks/execute.php
<?php echo CHtml::beginForm(); ?>
<br>
<b>Описание:</b> <?php echo $model->description;?>
<br>
<br>

<?php $this->widget('system.web.widgets.CTabView', array(
						'tabs'=>array(
							'tab1' => array(
								'title'=>'Описание',
								'content'=> CHtml::activeTextArea($model,'ex_description',array('class'=>'text_edit','style'=>'width:100%;height:150px')),
							),
							
							'tab2' => array(
								'title'=>'Работа',
								//'view'=>'_servicegrid',
								//'data'=>array('dataProvider'=>$dataProvider1),
							),
														
							'tab3' => array(
								'title'=>'Материалы',
								//'view'=>'_mattab',
								//'data'=>array('dataProvider'=>$dataProvider3),
								//'content'=> echo '<div>'; $this->renderPartial('_matgrid',array('dataProvider'=>$dataProvider3)); echo '</div>';,
							),
						),
					));
?>
<br>
<br>
<div id="body_execute">
<?php 
	//$this->renderPartial('_cachegrid',array('dataProvider'=>$dataProvider2));
?>
</div>


<br>

<?php
	echo CHtml::activeRadioButtonList($model,'state',array('0'=>'Работаю','1'=>'Подтвердить выполнение'));
?>		
	
<center>
	<?php echo chtml::SubmitButton('Сохранить',array('class'=>'bt','style'=>'width:90px;')); ?>
</center>
<?php echo CHtml::endForm(); ?>

views/tasks/index.php
<?php echo CHtml::link('Создать задачу...',array('create')); ?>
<br>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'itemview',
	'template'=>'{summary} {sorter} {pager} {items} {pager}',
)); ?>

views/tasks/indexbyexecutor.php
<?php $this->renderPartial('indexlinks');?>

<br>
<?php
$bf = -1;
    foreach ($model as $item){
	if($bf<>$item->id_executor){
	    if($item->id_executor == 0)
		echo '<br><b>Не распределенные</b>';
	    else
		echo '<br><b>'.CHtml::link($item->executor->person->name,array('users/details','id'=>$item->id_executor)).'</b>'; 
		//выводим название группы
		$bf = $item->id_executor;  
		}

$this->renderPartial('itemview',array('data'=>$item));
}
?>

views/tasks/indexbyorg.php
<?php $this->renderPartial('indexlinks');?>

<br>
<?php
$bf = -1;
    foreach ($model as $item){
	if($bf<>$item->id_kontragent){
	    if($item->id_kontragent == 0)
			echo '<br><b>Без организации</b>';
	    else
			echo '<br><b>'.CHtml::link($item->kontr->name,array('kontragents/details','id'=>$item->id_kontragent)).'</b>';  //выводим название группы
			$bf = $item->id_kontragent;  
		}

$this->renderPartial('itemview',array('data'=>$item));
}
?>

views/tasks/indexlinks.php
<?php 
if (!isset($_GET['timestamp']))
	echo CHtml::link('Создать задачу...',array('create')); 
else 
	echo CHtml::link('Создать задачу...',array('create','timestamp'=>$_GET['timestamp'])); 
?>
<br>
<?php
	echo CHtml::link('Форма для печати',Yii::app()->request->requestUri.'&print=1'); 	
?>

views/tasks/itemview.php
<div class=<?php echo 'task_s'.$data['state']; ?><?php if(Yii::app()->controller->action->id != 'details'){?> style="margin-left:30px;"<?php }?> >
	<?php echo '<b>№&nbsp;'.$data['id'].'&nbsp;&nbsp;['.date("d.m.y H:i",strtotime($data['startdate'])).']</b>';?>

	<?php if($data['important']==1){
				echo '<BLINK><FONT color="red"><b>ВАЖНО!!!</b></FONT></BLINK>';
			}?>

	&nbsp;&nbsp;
	<b>Автор:</b> <?php if($data['id_author']!=0) echo $data['author']->person->name;
							else echo 'Бот';?>
	
	
	<?php 
	
	$action = Yii::app()->controller->action->id; //Смотрим какой у нас акшен
	
	if  (($action == 'indexbyexecutor')||($action == 'details')) { //Если просмотр по исполнителю то показываем название организации 
	
		echo '&nbsp;&nbsp; <b>Организация:</b> ';
	
		if($data['id_kontragent']!=0) 
			echo CHtml::link($data['kontr']->name, array('kontragents/details','id'=>$data['id_kontragent']));
		else 
			echo '<BLINK><FONT color="green">Неизвестно!</FONT></BLINK>';// вот тут я добавил организацию
	
	} 
	elseif  ($action == 'indexbyorg') { //Если просмотр по организации то показываем имя исполнителя
	
		echo '&nbsp;&nbsp; <b>Исполнитель:</b> ';
		
		if($data['id_executor']!=0) 
			echo CHtml::link($data['executor']->person->name, array('users/details','id'=>$data['id_executor']));
			//echo $data['executor']->person->name;
		else 
			echo '<BLINK><FONT color="green">Неназначен!</FONT></BLINK>';
	
	}

	
	?>
		
	
	&nbsp;&nbsp;
	<b>Стоимость:</b> <?php echo $data['price'];?>
	<br>
	<div style="margin-left:30px;">
	<?php if(isset($data['description'])) echo $data['description']; ?>
	<?php if ($data['ex_description']) echo '<br>&nbsp;&nbsp;<b>>>></b>&nbsp;&nbsp;'.$data['ex_description']; ?>
	</div>

	<?php 
		//Смотрим файлы для этого задания
		$path_files='w_comty/files/tasks/'.$data['id'];
		if (file_exists($path_files)){

		    if ($countfiles = count(array_filter(glob("$path_files/*"), 'is_file')) > 0){

		$d = dir($path_files);
	?>

	<b>Файлы:</b>
	<br>
	<div style="margin-left:30px;">
	<?php 
		
		
		while (false !== ($entry = $d->read())) {
		    if (($entry !== '.')and($entry !== '..')){
			    echo CHtml::link($entry,$path_files.'/'.$entry);
			    echo '&nbsp;';
			    echo CHtml::link('(Удалить)',array('deluploadfile','id'=>$data['id'],'filename'=>$entry)).'<br>';
		    }
		}
		
		$d->close();?>
	</div>
	
	<?php
		}
	    }
	?>
	

	<!--Блок с кнопками управления-->
	<div class="task_bt">
		<?php 
		echo CHtml::link('(Добавить файл)',array('tasks/uploadfile','id'=>$data['id']));
		
		if (($data['state']==3)&&(Yii::app()->user->checkAccess('leader'))) //Если задача выполнена и ждет подтверждения выводим кнопарь для руководителей
			echo CHtml::link('(Подтвердить)',array('tasks/acceptexecute','id'=>$data['id'],'acpt'=>1));
		
		if (($data['state']!=3)&&($data['state']!=1)&&(Yii::app()->user->checkAccess('manager'))) //Если задача не выполнялась и пользователь менеджер то разрешаем редактировать
			echo CHtml::link('(Редактировать)',array('tasks/update','id'=>$data['id']));
		
		if ((($data['state']!=1)&&(Yii::app()->user->checkAccess('manager')))or(Yii::app()->user->checkAccess('superuser'))){ //Если задача не выполнялась менеджер и суперпользователь может удалять
			echo CHtml::link('(Удалить)',array('tasks/delete','id'=>$data['id']));
			}
		
		if (($data['state']<>1)and($data['state']<>3)and($data['id_executor'] == Yii::app()->user->getId())){ //Если задача не выполнялась и исполнитель текущий пользователь выводим кнопку
			 echo CHtml::link('(Выполнить)',array('tasks/execute','id'=>$data['id'])); }?>
			 
	</div>

</div>

views/tasks/itemviewprint.php
<div class='task_sp' <?php if(Yii::app()->controller->action->id != 'details'){?> style="margin-left:30px;"<?php }?> >
	<?php echo '<b>№&nbsp;'.$data['id'].'&nbsp;&nbsp;['.date("d.m.y H:i",strtotime($data['startdate'])).']</b>';?>

	<?php if($data['important']==1){
				echo '<BLINK><FONT color="red"><b>ВАЖНО!!!</b></FONT></BLINK>';
			}?>

	&nbsp;&nbsp;
	<b>Автор:</b> <?php if($data['id_author']!=0) echo $data['author']->person->name;
							else echo 'Бот';?>
	
	
	<?php 
	
	$action = Yii::app()->controller->action->id; //Смотрим какой у нас акшен
	
	if  (($action == 'indexbyexecutor')||($action == 'details')) { //Если просмотр по исполнителю то показываем название организации 
	
		echo '&nbsp;&nbsp; <b>Организация:</b> ';
	
		if($data['id_kontragent']!=0) 
			echo $data['kontr']->name;
		else 
			echo 'Неизвестно!';// вот тут я добавил организацию
	
	} 
	elseif  ($action == 'indexbyorg') { //Если просмотр по организации то показываем имя исполнителя
	
		echo '&nbsp;&nbsp; <b>Исполнитель:</b> ';
		
		if($data['id_executor']!=0) 
			echo $data['executor']->person->name;
			
		else 
			echo 'Неназначен!';
	
	}

	
	?>
		
	
	&nbsp;&nbsp;
	<b>Стоимость:</b> <?php echo $data['price'];?>
	<br>
	<div style="margin-left:30px;">
	<?php if(isset($data['description'])) echo $data['description']; ?>
	<?php if ($data['ex_description']) echo '<br>&nbsp;&nbsp;<b>>>></b>&nbsp;&nbsp;'.$data['ex_description']; ?>
	</div>
	

</div>

views/tasks/update.php
<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>